# Generated by Django 3.2.15 on 2022-10-08 11:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restomenu', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Menu',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='menu',
        ),
    ]
